[project]
name = "streifenstecker_xs"
version = "0.1.0"
description = "Describe your project here"
readme = "README.md"
requires-python = ">=3.10"

[project.optional-dependencies]
dev = ["pytest"]

[tool.pytest.ini_options]
pythonpath = ["src"]
